//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("HearthstoneTracker")]
[assembly: AssemblyDescription("HearthstoneTracker.com")]
[assembly: AssemblyCompany("HearthstoneTracker.com")]
[assembly: AssemblyProduct("HearthstoneTracker")]
[assembly: AssemblyCopyright("Copyright © 2014 - HearthstoneTracker.com")]
[assembly: AssemblyTrademark("HearthstoneTracker.com")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("51e88eaa-dc6b-4fbb-b6bf-046b04584e69")]
[assembly: AssemblyVersion("1.9.23.39449")]
[assembly: AssemblyFileVersion("1.9.23.39449")]


