// <auto-generated />
namespace HearthCap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class themename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themename));
        
        string IMigrationMetadata.Id
        {
            get { return "201408251353484_themename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
