// <auto-generated />
namespace HearthCap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-beta1-30206")]
    public sealed partial class decks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(decks));
        
        string IMigrationMetadata.Id
        {
            get { return "201402280405179_decks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
