// <auto-generated />
namespace HearthCap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201401080225106_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
