// <auto-generated />
namespace HearthCap.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21218")]
    public sealed partial class TextFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TextFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201401241936465_TextFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
